---
# =============================================================================
# Install Oracle GI 21.3 Software Only:
# (1) Assumption: Oracle GI software is downloaded and staged
# (2) modify required settings for oracle software installation
# =============================================================================


    - name: backup /etc/hosts
      shell: cp -p /etc/hosts /etc/hosts.`date +%Y%m%d`

    - name: backup /etc/sysctl.conf
      shell: cp -p /etc/sysctl.conf /etc/sysctl.conf.`date +%Y%m%d%H%M%S`

    - pam_limits:
        domain: grid
        limit_type: soft
        limit_item: nproc
        value: 2047

    - pam_limits:
        domain: grid
        limit_type: hard
        limit_item: nproc
        value: 16384

    - pam_limits:
        domain: grid
        limit_type: soft
        limit_item: nofile
        value: 1024

    - pam_limits:
        domain: grid
        limit_type: hard
        limit_item: nofile
        value: 65536

    - pam_limits:
        domain: grid
        limit_type: soft
        limit_item: stack
        value: 10240

    - pam_limits:
        domain: grid
        limit_type: hard
        limit_item: stack
        value: 10240


    - pam_limits:
        domain: oracle
        limit_type: soft
        limit_item: nproc
        value: 2047

    - pam_limits:
        domain: oracle
        limit_type: hard
        limit_item: nproc
        value: 16384

    - pam_limits:
        domain: oracle
        limit_type: soft
        limit_item: nofile
        value: 1024

    - pam_limits:
        domain: oracle
        limit_type: hard
        limit_item: nofile
        value: 65536

    - pam_limits:
        domain: oracle
        limit_type: soft
        limit_item: stack
        value: 10240

    - pam_limits:
        domain: oracle
        limit_type: hard
        limit_item: stack
        value: 10240
