---
# =============================================================================
# Install Oracle GI 21.3.0 Software Only:
# (1) Install Oracle GI 21.3.0 executeConfigTools in Silent Mode
# (2) Validate output logs 
# =============================================================================
- name: Install Oracle 21c GI ConfigTools in Silent Mode
  when: inventory_hostname in groups['ora-x1']
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/gridSetup.sh -silent -executeConfigTools -responseFile {{ stage_dir }}/{{ gi_rspfile }}"
  args:
      warn: false # set warn=false to prevent warning
  failed_when: racgi_configtools_result.rc != 255   #### This condition is based on my own setup
  register: racgi_configtools_result

- name: Get the log information
  remote_user: "{{ root_user }}"
  when: inventory_hostname in groups['ora-x1']
  shell: grep -r "'UpdateNodeList' was successful *" {{ ora_inventory }}/logs/UpdateNodeList*.log
  register: configtools_log

- debug: var=configtools_log.stdout_lines
  when: inventory_hostname in groups['ora-x1']
