---
  - name: DB RU | Stop services from the Database Home using srvctl Node2
    when: inventory_hostname in groups['ora-x1']
    shell: export ORACLE_HOME={{ oracle_home }}; export PATH=$PATH:$ORACLE_HOME/bin; rm -rf {{ state_dirn2 }}; srvctl stop home -o {{ oracle_home }} -s {{ state_dirn2 }}  -t immediate -n {{ node2 }}
    remote_user: "{{ oracle_user }}"
    ignore_errors: True

