---
###########################################################################################
# Summary Steps:
# Assumption:
# - required patches are downloaded and staged [ex: this case patch stage directory]
# - This case we are patching non-rolling GI Release Update and Database Release Update
#  1) execute pre-patch apply tasks
#  2) Apply GI RU 
#  3) Apply Database RU 
###########################################################################################
  - name: display pre GI RU and Database RU message
    debug:
      msg:
        - 'This playbook is for GI Release Update and Database Release Update 21.3 to 21.4 started at {{ansible_date_time.iso8601}}:'

  - name: Run pre-tasks before apply
    include: prepatch_apply.yml
    tags: pre_tasks_before_apply

  - name: RAC Patching | GI Release Update to grid home and db home on first node (opatchauto)
    include_tasks: ru_frstnode_gindb.yml

  - name: Restart cluster first node after applying GI RU
    include_tasks: restsrt_cluster_frstnode.yml

  - name: Restart cluster second node after applying RU
    include_tasks: restsrt_cluster_secnode.yml

  - name: display post GI RU and pre Database RU message
    debug:
      msg:
        - 'GI Release Update has been completed and Database Release Update will be in progress now at {{ansible_date_time.iso8601}}:'

  - name: RAC Patching | Pause after GI RU patching completion on first node
    pause: prompt="Verify First Node - Everything running OK or NOT." minutes=10

  - name: RAC Patching | GI Release Update to grid home and db home on second node (opatchauto)
    include_tasks: ru_secnode_gindb.yml

  - name: RAC Patching | DB Release Update to db home on first and then second node (opatchauto)
    include_tasks: db_ru_nodes.yml

  - name: Run post-tasks after patch
    include: postpatch_apply.yml
    tags: post_tasks_after_apply

  - name: Remove stage directory
    remote_user: "{{ root_user }}"
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ stage_dir }}"

  - name: display post GI RU message
    debug:
      msg:
        - 'This completed below task for RAC database at {{ansible_date_time.iso8601}}:'
        - 'Oracle Database Patch - GI Release Update and Database Release Update of Oracle 21.3 to 21.4 task completed successfully'
        - 'END OF ALL: git repository will be shared'
