---
  - name: Restart cluster stop
    when: inventory_hostname in groups['ora-x1']
    remote_user: "{{ root_user }}"
    shell: "{{ grid_home }}/bin/crsctl stop cluster"
    register: cluster_stop

  - name: Restart cluster start
    when: inventory_hostname in groups['ora-x1']
    remote_user: "{{ root_user }}"
    become: yes
    shell: "{{ grid_home }}/bin/crsctl start cluster"
    register: cluster_stop


