---
  - name: RAC Patching | unzip GI RU required patch file
    when: ('ora-x1' in group_names) or ('ora-x2' in group_names)
    remote_user: "{{ root_user }}"
    unarchive: src={{ patch_stage_dir }}/p33250101_210000_Linux-x86-64.zip dest={{ patch_unzipdir }} owner={{ grid_user }} group={{ oracle_install_group }} mode=0775 remote_src=no


  - name: RAC Patching | unzip DB RU required patch file
    when: ('ora-x1' in group_names) or ('ora-x2' in group_names)
    remote_user: "{{ root_user }}"
    unarchive: src={{ patch_stage_dir }}/p33239276_210000_Linux-x86-64.zip dest={{ patch_unzipdir }} owner={{ oracle_user }} group={{ oracle_install_group }} mode=0775 remote_src=no
